'use client';

import { useState } from 'react';

type Section = 'overview' | 'tenants' | 'moderation' | 'catalog' | 'stats' | 'audit';
const nav: { id: Section; label: string; icon: string }[] = [
  { id: 'overview', label: 'نظرة عامة', icon: '⌂' }, { id: 'tenants', label: 'المعارض', icon: '▣' }, { id: 'moderation', label: 'إشراف المركبات', icon: '◈' }, { id: 'catalog', label: 'الكتالوج', icon: '⌘' }, { id: 'stats', label: 'الإحصاءات', icon: '◒' }, { id: 'audit', label: 'سجل التدقيق', icon: '≡' }
];
const tenants = [{ name: 'معرض مسار النخبة', slug: 'elite-path', status: 'نشط ومعتمد', plan: 'PRO', vehicles: 42, leads: 128 }, { name: 'معرض الرياض الحديث', slug: 'riyadh-modern', status: 'بانتظار الاعتماد', plan: 'STARTER', vehicles: 18, leads: 44 }, { name: 'سيارات جدة المتحدة', slug: 'jeddah-united', status: 'موقوف', plan: 'STARTER', vehicles: 27, leads: 63 }];
const vehicles = [{ name: 'تويوتا كامري GLE', dealer: 'معرض مسار النخبة', status: 'بانتظار المراجعة', price: '124,500 ر.س' }, { name: 'مرسيدس E 200', dealer: 'الرياض الحديث', status: 'منشورة', price: '289,000 ر.س' }, { name: 'لكزس ES 350', dealer: 'مسار النخبة', status: 'معلّقة', price: '218,000 ر.س' }];
const audits = [{ action: 'اعتماد معرض', actor: 'منال القحطاني', entity: 'الرياض الحديث', time: 'منذ 12 دقيقة' }, { action: 'تفعيل خطة PRO', actor: 'أحمد الدوسري', entity: 'مسار النخبة', time: 'منذ ساعة' }, { action: 'تعليق مركبة', actor: 'منال القحطاني', entity: 'لكزس ES 350', time: 'منذ 3 ساعات' }];

export default function AdminHome() { const [section, setSection] = useState<Section>('overview'); const [menuOpen, setMenuOpen] = useState(false); const title = nav.find((item) => item.id === section)?.label ?? 'نظرة عامة'; return <div className="admin-shell"><aside className={`admin-sidebar ${menuOpen ? 'open' : ''}`}><div className="admin-brand"><span>س</span><div><strong>سيارات</strong><small>إدارة المنصة</small></div></div><div className="admin-profile"><span>م</span><div><strong>منال القحطاني</strong><small>Platform Operations</small></div></div><nav>{nav.map((item) => <button key={item.id} className={section === item.id ? 'active' : ''} onClick={() => { setSection(item.id); setMenuOpen(false); }}><i>{item.icon}</i>{item.label}</button>)}</nav><div className="admin-foot"><span className="secure-dot" />جلسة إدارية آمنة<small>آخر دخول: اليوم، 08:42</small></div></aside><main className="admin-main"><header className="admin-topbar"><button className="admin-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="فتح القائمة">☰</button><div><small>مساحة عمل Platform Staff</small><h1>{title}</h1></div><div className="admin-actions"><button aria-label="الإشعارات">♧<b /></button><span className="role-pill">Operations</span><span className="circle-avatar">م</span></div></header>{section === 'overview' && <Overview setSection={setSection} />}{section === 'tenants' && <Tenants />}{section === 'moderation' && <Moderation />}{section === 'catalog' && <Catalog />}{section === 'stats' && <Stats />}{section === 'audit' && <Audit />}</main></div>; }

function Overview({ setSection }: { setSection: (section: Section) => void }) { return <div className="admin-stack"><section className="admin-hero"><div><span>مرحباً منال</span><h2>صورة واضحة للمنصة،<br />وقرارات أسرع.</h2><p>تابعي أهم عمليات الاعتماد والإشراف من مكان واحد.</p></div><div className="hero-orbit">◒<span>✦</span></div></section><section className="admin-metrics"><AdminMetric label="المعارض النشطة" value="86" delta="+8.4% هذا الشهر" tone="green" /><AdminMetric label="بانتظار الاعتماد" value="12" delta="تحتاج مراجعة" tone="orange" /><AdminMetric label="سيارات منشورة" value="1,248" delta="+96 هذا الأسبوع" tone="blue" /><AdminMetric label="Leads هذا الشهر" value="3,842" delta="+12.6%" tone="purple" /></section><div className="admin-columns"><section className="admin-panel"><div className="admin-panel-head"><div><small>يحتاج قراراً</small><h3>طابور العمليات</h3></div><button onClick={() => setSection('tenants')}>عرض كل المعارض ←</button></div><div className="queue-list"><Queue icon="▣" title="12 معرضاً بانتظار الاعتماد" detail="أقدم طلب منذ 6 ساعات" action="مراجعة" onClick={() => setSection('tenants')} tone="orange" /><Queue icon="◈" title="27 سيارة بانتظار الإشراف" detail="تحتاج قرار نشر أو تعليق" action="فتح الطابور" onClick={() => setSection('moderation')} tone="blue" /><Queue icon="≡" title="آخر نشاط إداري منذ 12 دقيقة" detail="اعتماد معرض الرياض الحديث" action="السجل" onClick={() => setSection('audit')} tone="purple" /></div></section><section className="admin-panel"><div className="admin-panel-head"><div><small>النشاط</small><h3>آخر إجراءات الإدارة</h3></div><button onClick={() => setSection('audit')}>السجل الكامل ←</button></div>{audits.map((item) => <div className="audit-mini" key={item.action}><span className="audit-avatar">{item.actor[0]}</span><div><strong>{item.action}</strong><small>{item.entity} · {item.actor}</small></div><time>{item.time}</time></div>)}</section></div></div>; }
function AdminMetric({ label, value, delta, tone }: { label: string; value: string; delta: string; tone: string }) { return <div className="admin-metric"><span className={`metric-dot ${tone}`} /> <small>{label}</small><strong>{value}</strong><em>{delta}</em></div>; }
function Queue({ icon, title, detail, action, tone, onClick }: { icon: string; title: string; detail: string; action: string; tone: string; onClick: () => void }) { return <div className="queue-item"><span className={`queue-icon ${tone}`}>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><button onClick={onClick}>{action} ←</button></div>; }

function Tenants() { return <div className="admin-stack"><div className="admin-intro"><div><small>إدارة دورة حياة المعرض</small><h2>المعارض</h2><p>اعتمدي، أوقفي، وأديري خطط المعارض من لوحة واحدة.</p></div><button className="admin-primary">+ إضافة Platform Staff</button></div><div className="admin-filter"><input placeholder="ابحث باسم المعرض أو slug" aria-label="بحث المعارض" /><select defaultValue="all" aria-label="تصفية حالة المعرض"><option value="all">كل الحالات</option><option>بانتظار الاعتماد</option><option>نشط ومعتمد</option><option>موقوف</option></select></div><section className="admin-table"><div className="admin-table-head"><span>المعرض</span><span>الحالة</span><span>الخطة</span><span>المركبات</span><span>Leads</span><span /></div>{tenants.map((tenant) => <div className="admin-table-row" key={tenant.slug}><div className="admin-entity"><span>{tenant.name[0]}</span><div><strong>{tenant.name}</strong><small>{tenant.slug}</small></div></div><span className={`admin-badge ${tenant.status === 'نشط ومعتمد' ? 'green' : tenant.status === 'موقوف' ? 'red' : 'orange'}`}>{tenant.status}</span><span className="plan-badge">{tenant.plan}</span><strong>{tenant.vehicles}</strong><strong>{tenant.leads}</strong><button className="dots">⋮</button></div>)}</section></div>; }
function Moderation() { return <div className="admin-stack"><div className="admin-intro"><div><small>مراجعة المحتوى</small><h2>إشراف المركبات</h2><p>تأكدي من جودة السيارات قبل ظهورها في Marketplace العام.</p></div><span className="review-count">27 بانتظار المراجعة</span></div><section className="admin-table"><div className="admin-table-head"><span>المركبة</span><span>المعرض</span><span>السعر</span><span>الحالة</span><span /></div>{vehicles.map((vehicle) => <div className="admin-table-row vehicle-admin-row" key={vehicle.name}><div className="admin-entity"><span className="vehicle-placeholder">س</span><div><strong>{vehicle.name}</strong><small>مضاف منذ ساعتين</small></div></div><span>{vehicle.dealer}</span><strong>{vehicle.price}</strong><span className={`admin-badge ${vehicle.status === 'منشورة' ? 'green' : vehicle.status === 'معلّقة' ? 'red' : 'orange'}`}>{vehicle.status}</span><button className="moderate-button">مراجعة</button></div>)}</section></div>; }
function Catalog() { return <div className="admin-stack"><div className="admin-intro"><div><small>البيانات العامة</small><h2>الكتالوج</h2><p>إدارة الماركات والموديلات والمدن التي تعتمد عليها المنصة.</p></div><button className="admin-primary">+ إضافة عنصر</button></div><div className="catalog-tabs"><button className="active">الماركات <b>48</b></button><button>الموديلات <b>312</b></button><button>المدن <b>13</b></button></div><section className="catalog-grid">{['تويوتا', 'هيونداي', 'لكزس', 'مرسيدس بنز', 'فورد', 'نيسان'].map((brand, index) => <div className="catalog-card" key={brand}><span className="brand-letter">{brand[0]}</span><div><strong>{brand}</strong><small>{index * 12 + 18} موديل · نشطة</small></div><button>⋮</button></div>)}</section></div>; }
function Stats() { return <div className="admin-stack"><div className="admin-intro"><div><small>تحليل المنصة</small><h2>إحصاءات Leads</h2><p>مؤشرات أساسية لفهم أداء الطلبات عبر المعارض.</p></div><select defaultValue="30" aria-label="الفترة الزمنية"><option value="30">آخر 30 يوماً</option><option value="7">آخر 7 أيام</option></select></div><section className="admin-metrics stats-metrics"><AdminMetric label="إجمالي Leads" value="3,842" delta="هذا الشهر" tone="purple" /><AdminMetric label="معدل التحويل" value="18.6%" delta="+2.1% من الشهر الماضي" tone="green" /><AdminMetric label="متوسط الاستجابة" value="2.4 س" delta="-18 دقيقة" tone="blue" /></section><section className="admin-panel chart-panel"><div className="admin-panel-head"><div><small>الطلبات الواردة</small><h3>حركة Leads اليومية</h3></div><span className="chart-legend">● Leads جديدة</span></div><div className="fake-chart"><div className="chart-bars">{[42, 57, 39, 72, 63, 88, 66, 78, 95, 72, 84, 91].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>١ أغسطس</span><span>٧ أغسطس</span><span>١٤ أغسطس</span><span>اليوم</span></div></div></section></div>; }
function Audit() { return <div className="admin-stack"><div className="admin-intro"><div><small>الامتثال والشفافية</small><h2>سجل التدقيق</h2><p>سجل غير قابل للتعديل لكل إجراء إداري حساس.</p></div><button className="secondary-admin">تصدير السجل</button></div><section className="admin-table audit-table"><div className="admin-table-head"><span>الإجراء</span><span>المنفذ</span><span>العنصر</span><span>التوقيت</span><span /></div>{audits.concat(audits).map((item, index) => <div className="admin-table-row" key={`${item.action}-${index}`}><div className="audit-action"><span className="action-icon">✓</span><strong>{item.action}</strong></div><span>{item.actor}</span><span>{item.entity}</span><small>{item.time}</small><button className="dots">⋮</button></div>)}</section></div>; }
